routes/web.php
<?php
Route::get('/', function () {
    return view('welcome');
});

Route::resource('deplacements', 'deplacementController');

app/deplacement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Deplacement extends Model
{
     protected $fillable = [
        'nom',
        'prenom',
        'email',
        'id_ville',
        'id_moyen',
        'datededepart',
        'heurededepart',
        'datederetour',
        'heurederetour'      
    ];

   public function ville(){
         return $this->hasOne(ville::class);
    }
   public function moyen(){
         return $this->hasOne(moyen::class);
    }


}

app/Http/Controllers/deplacementController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\deplacement;
use App\ville;
use App\moyen;

class deplacementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $deplacements = deplacement::all();
        $ville = ville::all();
        $moyen = moyen::all();

        return view('deplacements.index', compact('deplacements','ville','moyen'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
     $deplacements = deplacement::all();
     $ville = ville::all();
     $moyen = moyen::all();   
     return view('deplacements.create', compact('deplacements','ville','moyen'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
          $request->validate([
            'nom'=>'required',
            'prenom'=>'required',
            'email'=>'required'
        ]);

        $deplacement = new deplacement([
            'nom' => $request->get('nom'),
            'prenom' => $request->get('prenom'),
            'email' => $request->get('email'),
            'id_ville' => $request->get('id_ville'),
            'id_moyen' => $request->get('id_moyen'),
            'datededepart' => $request->get('datededepart'),
            'datederetour' => $request->get('datederetour'),
            'heurededepart' => $request->get('heurededepart'),
            'heurederetour' => $request->get('heurederetour')
        ]);
        $deplacement->save();
        return redirect('/deplacements')->with('success', 'deplacement saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $deplacement = deplacement::find($id);

        // show the view and pass the nerd to it
        return view('deplacements.show',compact('deplacement',$deplacement));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $deplacement = deplacement::find($id);
        return view('deplacements.edit', compact('deplacement'));  
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nom'=>'required',
            'prenom'=>'required',
            'email'=>'required'
        ]);

        $deplacement = deplacement::find($id);
        $deplacement->nom =  $request->get('nom');
        $deplacement->prenom = $request->get('prenom');
        $deplacement->email = $request->get('email');
        $deplacement->id_ville = $request->get('id_ville');
        $deplacement->id_moyen = $request->get('id_moyen');
        $deplacement->datededepart = $request->get('datededepart');
        $deplacement->datederetour = $request->get('datederetour');
        $deplacement->heurededepart = $request->get('heurededepart');
        $deplacement->heurederetour = $request->get('heurederetour');
        $deplacement->save();

        return redirect('/deplacements')->with('success', 'deplacement updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         $deplacement = deplacement::find($id);
         $deplacement->delete();

        return redirect('/deplacements')->with('success', 'Deplacements deleted!');
    }
}

resources/views/deplacements/create.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Ajouter un deplacement</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('deplacements.store') }}">
          @csrf
          <div class="form-group">    
              <label for="nom">Nom:</label>
              <input type="text" class="form-control" name="nom"/>
          </div>

          <div class="form-group">
              <label for="prenom">Prenom:</label>
              <input type="text" class="form-control" name="prenom"/>
          </div>

          <div class="form-group">
              <label for="email">Email:</label>
              <input type="email" class="form-control" name="email"/>
          </div>
         <div class="form-group">
              <label for="city">Ville :</label>
              <select name="id_ville">
 <?php foreach ($ville as $ville) {
?>
    <option value="<?php echo $ville->id; ?>"><?php echo $ville->ville; ?></option>
 <?php }
?>
</select>
          </div>
          <div class="form-group">
              <label for="city">Ville :</label>
              <select name="id_moyen">
 <?php foreach ($moyen as $moyen) {
?>
    <option value="<?php echo $moyen->id; ?>"><?php echo $moyen->moyen; ?></option>
 <?php }
?>
</select>
          </div>
          <div class="form-group">
              <label for="datededepart">Date de depart:</label>
              <input type="date" class="form-control" name="datededepart"/>
          </div>    
          <div class="form-group">
              <label for="datederetour">Date de retour:</label>
              <input type="date" class="form-control" name="datederetour"/>
          </div>    
          <div class="form-group">
              <label for="heurededepart">Heure de depart:</label>
              <input type="time" class="form-control" name="heurededepart"/>
          </div>    
          <div class="form-group">
              <input type="time" class="form-control" name="heurederetour"/>
          </div>                         
          <button type="submit" class="btn btn-primary-outline">Ajouter</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/deplacements/edit.blade.php
@extends('base')

@section('main')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit deplacement
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('deplacements.update', $deplacement->id) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
          <label for="name">Nom:</label>
          <input type="text" class="form-control" name="nom" value={{ $deplacement->nom }} />
        </div>
        <div class="form-group">
          <label for="prenom">Prenom:</label>
          <input type="text" class="form-control" name="prenom" value={{ $deplacement->prenom }} />
        </div>
        <div class="form-group">
          <label for="email">Email:</label>
          <input type="text" class="form-control" name="email" value={{ $deplacement->email }} />
        </div>
        <div class="form-group">
          <label for="ville">Ville:</label>
          <input type="text" class="form-control" name="id_ville" value={{ $deplacement->id_ville }} />
        </div>
        <div class="form-group">
          <label for="moyen">Moyen:</label>
          <input type="text" class="form-control" name="id_moyen" value={{ $deplacement->id_moyen }} />
        </div>
        <div class="form-group">
          <label for="datededepart">Date de depart:</label>
          <input type="text" class="form-control" name="datededepart" value={{ $deplacement->datededepart }} />
        </div>
        <div class="form-group">
          <label for="datederetour">Date de retour:</label>
          <input type="text" class="form-control" name="datederetour" value={{ $deplacement->datederetour }} />
        </div>
        <div class="form-group">
          <label for="heurededepart">Heure de depart:</label>
          <input type="text" class="form-control" name="heurededepart" value={{ $deplacement->heurededepart }} />
        </div>
        <div class="form-group">
          <label for="heurederetour">Heure de retour:</label>
          <input type="text" class="form-control" name="heurederetour" value={{ $deplacement->heurederetour }} />
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@endsection

resources/views/deplacements/index.blade.php
@extends('base')

@section('main')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Deplacements</h1>   
<div>
    <a style="margin: 19px;" href="{{ route('deplacements.create')}}" class="btn btn-primary">New deplacement</a>
    </div>  
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Nom</td>
          <td>Prenom</td>
          <td>Email</td>
          <td>Ville</td>
          <td>Moyen</td>
          <td>Date de depart</td>
          <td>Date de retour</td>
          <td>Heure de depart</td>
          <td>Heure de retour</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($deplacements as $deplacement)
        <tr>
            <td>{{$deplacement->id}}</td>
            <td>{{$deplacement->nom}}</td>
            <td>{{$deplacement->prenom}}</td>
            <td>{{$deplacement->email}}</td>
            <td>{{$deplacement->id_ville}}</td>
            <td>{{$deplacement->id_moyen}}</td>
            <td>{{$deplacement->datededepart}}</td>
            <td>{{$deplacement->datederetour}}</td>
            <td>{{$deplacement->heurededepart}}</td>
            <td>{{$deplacement->heurederetour}}</td>
            <td>
                <a href="{{ route('deplacements.edit',$deplacement->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <form action="{{ route('deplacements.destroy', $deplacement->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div> 
</div>
@endsection

resources/views/deplacements/show.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Look! I'm CRUDding</title>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
</head>
<body>
<div class="container">

<nav class="navbar navbar-inverse">
    <div class="navbar-header">
        <a class="navbar-brand" href="{{ URL::to('deplacements') }}">Deplacement</a>
    </div>
    <ul class="nav navbar-nav">
        <li><a href="{{ URL::to('deplacements') }}">View All deplacements</a></li>
        <li><a href="{{ URL::to('deplacements/create') }}">Ajouter deplacement</a>
    </ul>
</nav>

<h1>le deplacement de {{ $deplacement->nom }} {{ $deplacement->prenom }}</h1>

    <div class="jumbotron text-center">
        <strong>Nom:</strong> {{ $deplacement->nom }} <br>
        <p> 
            <strong>Prenom:</strong> {{ $deplacement->prenom }}<br>
            <strong>Email:</strong> {{ $deplacement->email }}<br>
            <strong>Ville:</strong> {{ $deplacement->id_ville }}<br>
            <strong>Moyen:</strong> {{ $deplacement->id_moyen }}<br>
            <td>d.depart: {{$deplacement->datededepart}}</td>
            <td>d.retour: {{$deplacement->datederetour}}</td>
            <td>h.depart: {{$deplacement->heurededepart}}</td>
            <td>h.retour: {{$deplacement->heurederetour}}</td>
        </p>
    </div>

</div>
</body>
</html>